# Generated by Django 3.1.1 on 2020-09-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_name', models.CharField(default=' ', max_length=200)),
                ('poll_description', models.TextField(default=' ')),
                ('poll_options', models.TextField(default='{}')),
                ('poll_result', models.TextField(default='{}')),
            ],
        ),
    ]
