# Generated by Django 3.1.1 on 2020-09-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_options',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_result',
            field=models.TextField(default='[]'),
        ),
    ]
